language: go
go:
- 1.6.3
- 1.7.1
- tip
script:
- go test
- go tool vet -v -all .
branches:
  only:
  - master
notifications:
  irc:
    channels:
    - irc.byteirc.org#L
    template:
    - "%{repository} #%{build_number} %{branch}/%{commit}: %{author} -- %{message}
      %{build_url}"
    on_success: change
    on_failure: change
    skip_join: true
